#include "Meta.h"
#include "FO.h"
#include "GreedyMatching.h"

template <typename Move>
MetaBase<Move>::MetaBase(const std::unordered_map<Move, string>& moves, const std::unordered_map<Move, double>& weights, std::mt19937& g): 
          Moves(moves), Weights(weights), gen(g) {
            double sum = 0;
            cout << "------ Cumulative Weights ------" << endl;
            for (const auto& [move, weight]: weights){
                sum += weight;
                WeightsCumul[sum] = move;

                cout << "Cumulative weight of " << Moves.at(WeightsCumul.at(sum)) << " = " << sum << endl;
                
                NrImprov[move] = 0;
                NrChosen[move] = 0;
                NrImprovBestObj[move] = 0; 
                Reward[move] = 0;
                NrAccepted[move] = 0;
                SelectionProbabilityMAB[move] = 0;
                Improv[move]; // vector is default constructed
                ExecutionTimes[move];
            }
            cout << "-------------------------------" << endl;
            assert(0.99 < sum && sum < 1.01);
            it = 0;
            it_accepted = 0;
            it_idle = 0;
            best_obj = INT_MAX;
            current_obj = INT_MAX;
        }

template <typename Move>
void MetaBase<Move>::UpdateBestSolution(Solution& sol){
            int j,h,a;
            for (int r = 0; r < sol.getNrRounds(); ++r){
                for (int i = 0; i < sol.getNrTeams(); ++i){
                    j = sol.TeamColorOpp[i][r];
                    if (i < j){
                        continue;
                    }
                    if (!sol.ViolationEligibleOpponents_allowed){
                        assert(sol.isEligible(i,j));
                    }
                    if (sol.Orientation[i][r] == HA::H){
                        assert(sol.Orientation[j][r] == HA::A);
                        h = i, a = j;
                    }
                    else{
                        assert(sol.Orientation[j][r] == HA::H);
                        assert(sol.Orientation[i][r] == HA::A);
                        h = j, a = i;
                    }
                    BestOrientation[h][r] = HA::H;
                    BestOrientation[a][r] = HA::A;
                    BestTeamColorOpp[h][r] = a;
                    BestTeamColorOpp[a][r] = h;
                }
            }
            // cout << "New best solution value = " << sol.ComputeTotalCost() << endl;
        }


template <typename Move>
void MetaBase<Move>::SaveBestSolution(Solution& sol){
            int h,a,j;
            // first, clear everything
            sol.clear();
            for (int r = 0; r < sol.getNrRounds(); ++r){
                for (int i = 0; i < sol.getNrTeams(); ++i){
                    j = BestTeamColorOpp[i][r];
                    if (i < j){
                        continue;
                    }
                    if (BestOrientation[i][r] == HA::H){
                        assert(BestOrientation[j][r] == HA::A);
                        h = i, a = j;
                    }
                    else{
                        assert(BestOrientation[i][r] == HA::A);
                        assert(BestOrientation[j][r] == HA::H);
                        h = j, a = i;
                    }
                    SetValueCircleMethod(h, a, r, sol);
                    sol.Orientation[h][r] = HA::H; 
                    sol.Orientation[a][r] = HA::A;
                }
            }
            assert(sol.validate());
            // cout << "saved solution" << endl;
        }

template <typename Move>
        void MetaBase<Move>::UpdateValues(Solution& sol, const int obj){
            NrAccepted.at(CurrentMove)++; // this is about whether the move is accepted, not the solution generated by the move
#ifdef PRINT
#if PRINT == 1
	    	// At this point current_obj has not yet been updated
		// --> postpone printing
                //print_solution();
#endif
#endif
            assert(best_obj <= current_obj);
            if (obj < best_obj){
                best_obj = obj;
#ifdef PRINT
#if PRINT == 1
                cout << "NEW BEST SOLUTION = " << best_obj << endl;
#endif
#endif
                NrImprovBestObj.at(CurrentMove)++;
                UpdateBestSolution(sol); // We need to store the best solution somewhere
                TimeTillBestSolution = (int)getTimeDiff();
            }
            if (obj <= current_obj){
                // cout << "Accept solution" << endl;
                if (obj < current_obj){
                    NrImprov.at(CurrentMove)++;
                    Improv.at(CurrentMove).push_back(current_obj-obj);
                    UpdateReward(CurrentMove);
                }
            }

	}

template <typename Move>
        void MetaBase<Move>::SaveResultsMoves(std::string file_path_results_base, int instance, int seed){
            std::string file_path_results_performance = file_path_results_base + std::string(PATHSEP) + "Performance" + std::string(PATHSEP) + to_string(instance) + "_" + to_string(seed) + ".txt";
            std::ofstream file(file_path_results_performance);
            file << "Move, NrChosen, NrAccepted, % Times improvement found, Average improvement found, % Times contribution to best objective, Instance, Seed\n";
            // cout << "Move, NrChosen, NrAccepted, % Improvement found, Average improvement found, % contribution to best objective" << endl;
            for (const auto& [move, string_name]: Moves){
                if (string_name == "Initial"){
                    continue;
                }
                // cout << string_name << ", " << NrChosen.at(move) << ", " << NrAccepted.at(move) << ", " << (double) NrImprov.at(move) / (double) NrChosen.at(move) << ", " << (double) Reward.at(move) / (double) NrChosen.at(move) << ", " << (double) NrImprovBestObj.at(move) / (double) NrChosen.at(move)  << endl;
                file << string_name << ",";
                file << NrChosen.at(move) << ",";
                file << NrAccepted.at(move) << ",";
                file << (double) NrImprov.at(move) / (double) NrChosen.at(move) << ",";
                file << (double) Reward.at(move) / (double) NrImprov.at(move) << ",";
                file << (double) NrImprovBestObj.at(move) / (double) NrChosen.at(move) << ",";
                file << instance << "," << seed << "\n";
            }
            file.close();
   
            std::string file_path_results_time= file_path_results_base + std::string(PATHSEP) + "ExecutionTime" + std::string(PATHSEP) + to_string(instance) + "_" + to_string(seed) + ".txt";
            std::ofstream file2(file_path_results_time);
            file2 << "Move,Min,Max,Mean,Instance,Seed\n";
            // cout << "Move, NrChosen, NrAccepted, % Improvement found, Average improvement found, % contribution to best objective" << endl;
            for (const auto& [move, string_name]: Moves){
                if (string_name == "Initial" || ExecutionTimes.at(move).empty()){
                    continue;
                }
                array<std::chrono::microseconds,3>MinMaxMean = MinMaxMeanExecutionTime(move);
                file2 << MinMaxMean[0].count() << ",";
                file2 << MinMaxMean[1].count() << ",";
                file2 << MinMaxMean[2].count() << ",";
                file2 << instance << "," << seed << "\n";
                /*
                for (auto dur: ExecutionTimes.at(move)){ // store these as well to make boxplots later?
                    file2 << dur.count() << "\n";
                }
                */
            }
            file2.close();
        }


template<typename Move>
void MetaBase<Move>::UpdateBest(Solution& sol, const int obj){
    NewBestSolutionFound = false;
    if (obj < best_obj){
        best_obj = obj;
        UpdateBestSolution(sol);
        it_idle_best = 0;
        NewBestSolutionFound = true;
    }
    else{
        ++it_idle_best;
    }
}

template<typename Move>
bool LAHC<Move>::Update(Solution& sol, const int obj) {
           // code based on Burke (2017) "The late acceptance Hill-Climbing Heuristic"

            bool SolutionAccepted = false;
            int v = this->it % HistoryLength;
            /*
            cout << "L = ";
            for (int w = 0; w < this->HistoricValues.size(); ++w){
                if (w != v){
                    cout << w << ") " << this->HistoricValues.at(w) << " ";
                }
                else{
                    cout << w << ")** " << this->HistoricValues.at(w) << " ";
                }
            }
            cout << endl;
            cout << "Found obj = " << obj << ", current_obj = " << this->current_obj << ", it_idle = " << this->it_idle << endl;
            */

            // this->UpdateValues(sol, obj); -> UpdateBestSolution is now in other function!

            if (obj >= this->current_obj){
                /*
                if (PerturbeValue > 1){
                    cout << "obj = " << obj << endl;
                    cout << "current_obj = " << this->current_obj << endl;
                }
                */
                this->it_idle++;
            }
            else{
                // cout << "Reset idle to 0" << endl;
                this->it_idle = 0;
            }
            bool diff = false;
            if (obj <= this->current_obj || obj < HistoricValues.at(v)){

                if (obj != this->current_obj){
                    diff = true;
                }

                this->current_obj = obj; 
                this->it_accepted++;
                SolutionAccepted = true;
                this->NrAccepted.at(this->CurrentMove)++;
                // cout << "Accept solution" << endl;
            }
            if (obj < HistoricValues.at(v)){
                HistoricValues.at(v) = obj;
            }

            this->UpdateTimeStamps();
#ifdef PRINT
#if PRINT == 1
            if (SolutionAccepted && diff){
                this->print_solution();
            }
#endif
#endif

            ++this->it;
            return SolutionAccepted;

}

template<typename Move>
bool LAHC<Move>::UpdateListLength(Solution& sol) {

            if (this->NewBestSolutionFound){
               HistoryLength = 10;
               // it_same_HL = 0;
               PerturbeValue = PerturbeValue_INITIAL;
               this->it = 0;
               int lb = this->best_obj;
               int ub = PerturbeValue*this->best_obj;
               InitializeHistoricValues(lb, ub, HistoryLength);
            }

            ++this->it;
            if (this->getTimeDiff() > this->TIME_LIMIT || (this->it_idle > MAX_IT)){
                if (this->getTimeDiff() > this->TIME_LIMIT){
                    cout << "Time limit hit" << endl;
                    this->STOP = true;
                }
                else{
#ifdef PRINT
#if PRINT == 1
                    // cout << "max it_idle hit: " << this->it_idle << endl;
#endif
#endif
                    if (!DynamicHL){
                        this->STOP = true;
                    }
                    else{
#ifdef PRINT
#if PRINT == 1
                        // cout << "-------------------------" << endl;
#endif  
#endif                  

                        if (HistoryLength*HistoryMultiplier < MAX_HL){
                            HistoryLength *= HistoryMultiplier;
                            /*
                            I manually tried different things here, i.e. x2, additively add HL (+10 everytime), gradually increase HL (+10 till HL = 100, +100 till HL = 1000, +1000 til HL = 10000) on 3 instances, but they did not directly seem to result in better solutions
                            I similarly tried different things with PerturbeIncrease (e.g. trying the same HL but with different values for PerturbeIncrease, but this seemed too slow). 
                            */
#ifdef PRINT
#if PRINT == 1
                            cout << "New HistoryLength = " << HistoryLength << endl;
#endif
#endif
                        }
                        else{
                            // reinitialize
                            this->SaveBestSolution(sol);
                            this->current_obj = this->best_obj;
                            HistoryLength = 10;
                            // it_same_HL = 0;
                            PerturbeValue = 1.20;
                            this->it = 0;
                            int lb = this->best_obj;
                            int ub = PerturbeValue*this->best_obj;
                            InitializeHistoricValues(lb, ub, HistoryLength);
                        }
#ifdef PRINT
#if PRINT == 1
                        // cout << "Previous HL = " << HistoryLength << endl;
                        // cout << "New HL = " << HistoryLength << endl;
                        // cout << "Previous PerturbValue = " << PerturbeValue << endl;
#endif
#endif

#ifdef PRINT
#if PRINT == 1
                        // cout << "New PerturbValue = " << PerturbeValue << endl;
                        // cout << "Best obj = " << this->best_obj << endl;
                        // cout << "Initialize list with " << PerturbeValue*this->best_obj << endl;
#endif
#endif                  
                        PerturbeValue += PerturbeIncrease;
                        // cout << "current_obj = " << this->current_obj << ", TotalCost = " << sol.ComputeTotalCost() << endl;
                        this->SaveBestSolution(sol);
                        this->current_obj = this->best_obj;
                        // cout << "current_obj = " << this->current_obj << ", TotalCost = " << sol.ComputeTotalCost() << endl;
                        int Lb = this->current_obj;
                        int Ub = PerturbeValue*this->current_obj;
                        
                        InitializeHistoricValues(Lb, Ub, HistoryLength);
#ifdef PRINT
#if PRINT == 1
                        /*
                        cout << "---- Historic values ----" << endl;
                        for (auto& v: HistoricValues){
                            cout << v << ", ";
                        }
                        cout << endl;
                        cout << "-------------------------" << endl;
                        */

                        /*
                        cout << "Nr times Neighborhoods are selected" << endl;
                        for (const auto& [move, nr]: this->NrChosen){
                            cout << this->Moves.at(move) << " is chosen " << nr << " times, but accepted only " << this->NrAccepted.at(move) << " times" << endl;
                        }
                        cout << "-------------------------" << endl;
                        */
#endif
#endif
                        // cin.get();
 
                        this->it_idle = 0;
                        this->it = 0;

                        ResetSolutionAfterMove = false;
                        // cin.get();
                    }
                }
            }

            // cin.get();
            return true;

}

template<typename Move>
bool SA<Move>::Update(Solution& sol, const int obj){
            // cout << "prev_obj = " << current_obj << ", new obj = " << obj << endl;

            if (this->getTimeDiff() > this->TIME_LIMIT || T < T_end){
                this->STOP = true;
                if (this->getTimeDiff() > this->TIME_LIMIT){
                    cout << "Time limit hit" << endl;
                }
                else{
                    cout << "Final temperature hit after " << this->getTimeDiff() << " seconds" << endl;
                }
                // cin.get();
            }

            this->UpdateValues(sol, obj);
            bool SolutionAccepted = false;
            if (obj <= this->current_obj){
                this->current_obj = obj; 
                this->it_accepted++;
                SolutionAccepted = true;
            }
            else{
                this->dist_real = std::uniform_real_distribution<>(0.0, 1.0);
                double rnd = this->dist_real(this->gen);
                if (rnd <= exp(-(obj-this->current_obj)/T) && obj < INT_MAX-10){ // Metropolis acceptance
                    // cout << "Accept solution with prob " << exp(-(obj-current_obj)/T) << ", prev_obj = " << current_obj << ", new obj = " << obj << endl;
                    this->current_obj = obj;
                    this->it_accepted++;
                    SolutionAccepted = true;
                }
                else{
                    // reverse move
                    // We only need to reverse the haps since the matchings are thrown away anyway
                    // cout << "Reject solution with prob " << exp(-(obj-current_obj)/T) << endl;
                    SolutionAccepted = false; // CUSTOMIZE WHAT HAPPENS AFTERWARDS
                }
            }
            if (SolutionAccepted){
#ifdef PRINT
#if PRINT == 1
                    this->print_solution();
#endif
#endif
            }

            this->UpdateTimeStamps();

            if (++this->it % I_temp == 0 || (this->it_accepted - I_accept >= 0)){ 
                T *= cooling_rate;
#ifdef PRINT
#if PRINT == 1
                cout << "New T = " << T << endl;
#endif
#endif
                this->it_accepted = 0;
                this->it = 0;
            }
            return SolutionAccepted;
}


template<typename Move>
bool HC<Move>::Update(Solution& sol, const int obj){
            
            // cout << "prev_obj = " << this->current_obj << ", new obj = " << obj << endl;

            if (obj >= this->current_obj){
                this->it_idle++;
                if (this->it_idle % 10000 == 0 && this->it_idle > 0){
                    cout << "it_idle = " << this->it_idle << endl;
                }
            }
            else{
                this->it_idle = 0;
                #ifdef PRINT
#if PRINT == 1
                    this->print_solution();
#endif
#endif
            }

            if (this->getTimeDiff() > this->TIME_LIMIT){
                cout << "Time limit of " << this->TIME_LIMIT << " hit" << endl;
                this->STOP = true;
            }
            else if (this->it_idle > MAX_IT){
                cout << "it_idle = " << this->it_idle << ", MAX_IT = " << MAX_IT << endl;
                this->STOP = true;
            }

            this->UpdateValues(sol, obj);
            bool SolutionAccepted = false;
            if (obj <= this->current_obj){
                this->current_obj = obj; 
                this->it_accepted++;
                SolutionAccepted = true;
            }

            this->UpdateTimeStamps();

            return SolutionAccepted;
}

template<typename Move>
bool ILS<Move>::Update(Solution& sol, const int obj){

            bool SolutionAccepted = false;

            if (this->current_obj < obj && !this->PERTURBE){
                ++this->it_idle;
            }
            if (this->current_obj >= obj || (this->PERTURBE && obj < 3*sol.getCostTTPViolation()-100)){
                this->current_obj = obj;
                SolutionAccepted = true;

                if (this->PERTURBE){
                    it_accepted_perturbation++;
                }
#if PRINT == 1
                    this->print_solution();
#endif
            }

            if (this->getTimeDiff() > this->TIME_LIMIT){
                cout << "Time limit of " << this->TIME_LIMIT << " hit" << endl;
                this->STOP = true;
            }

            this->UpdateTimeStamps();

            return SolutionAccepted;
}


// Explicit instantiations
template class MetaBase<FO_move>;
template class MetaBase<Move>;
template class LAHC<Move>;
template class SA<FO_move>;
template class SA<Move>;
template class HC<Move>;
template class ILS<Move>;
