#include "Meta.h"
#include "FO.h"
#include "MiaoAlgo.h"

template <typename Move>
MetaBase<Move>::MetaBase(const std::unordered_map<Move, string>& moves, const std::unordered_map<Move, double>& weights, std::mt19937& g): 
          Moves(moves), Weights(weights), gen(g) {
            double sum = 0;
            cout << "------ Cumulative Weights ------" << endl;
            for (const auto& [move, weight]: weights){
                sum += weight;
                WeightsCumul[sum] = move;

                cout << "Cumulative weight of " << Moves.at(WeightsCumul.at(sum)) << " = " << sum << endl;
                
                NrImprov[move] = 0;
                NrChosen[move] = 0;
                NrImprovBestObj[move] = 0; 
                Reward[move] = 0;
                NrAccepted[move] = 0;
                Improv[move]; // vector is default constructed
                ExecutionTimes[move];
            }
            cout << "-------------------------------" << endl;
            assert(0.99 < sum && sum < 1.01);
            it = 0;
            it_accepted = 0;
            it_idle = 0;
            best_obj = INT_MAX;
            current_obj = INT_MAX;
        }

template <typename Move>
void MetaBase<Move>::UpdateBestSolution(Solution& sol){
            if (BestSequenceMatches.empty()){
                BestSequenceMatches = vector<vector<pair<int,int>>>(sol.getNrRounds(), vector<pair<int,int>>(sol.getNrTeams()/2));
            }
            int m, j, h, a;
            for (int r = 0; r < sol.getNrRounds(); ++r){
                vector<bool>TeamSeen(sol.getNrTeams(), false);
                m = 0;
                for (int i = 0; i < sol.getNrTeams(); ++i){
                    if (TeamSeen[i]){
                        continue;
                    }
                    j = sol.TeamColorOpp[i][r];
                    if (!sol.ViolationEligibleOpponents_allowed){
                        assert(sol.isEligible(i,j));
                    }
                    if (sol.Orientation[i][r] == HA::H){
                        assert(sol.Orientation[j][r] == HA::A);
                        h = i, a = j;
                    }
                    else{
                        assert(sol.Orientation[j][r] == HA::H);
                        assert(sol.Orientation[i][r] == HA::A);
                        h = j, a = i;
                    }
                    TeamSeen[h] = true;
                    TeamSeen[a] = true;
                    BestSequenceMatches[r][m++] = {h,a};
                }
            }
        }


template <typename Move>
void MetaBase<Move>::SaveBestSolution(Solution& sol){
            int h,a;
            if (BestSequenceMatches.empty()){
                cout << "Failed to find a solution, abort.." << endl;
                std::exit(0);
            }
            // first, clear everything
            sol.clear();
            for (int r = 0; r < sol.getNrRounds(); ++r){
                assert(BestSequenceMatches[r].size() == sol.getNrTeams()/2);
                for (auto& pair: BestSequenceMatches[r]){
                    h = pair.first, a = pair.second;
                    assert(sol.isEligible(h,a));
                    SetValueCircleMethod(h, a, r, sol);
                    sol.Orientation[h][r] = HA::H; // the orientation in this solution is also different!
                    sol.Orientation[a][r] = HA::A;
                }
            }
            assert(sol.validate());
        }

template <typename Move>
        void MetaBase<Move>::UpdateValues(Solution& sol, const int obj){
            NrAccepted.at(CurrentMove)++; // this is about whether the move is accepted, not the solution generated by the move
#ifdef PRINT
#if PRINT == 1
	    	// At this point current_obj has not yet been updated
		// --> postpone printing
                //print_solution();
#endif
#endif
            assert(best_obj <= current_obj);
            if (obj < best_obj){
                best_obj = obj;
#ifdef PRINT
#if PRINT == 1
                cout << "NEW BEST SOLUTION = " << best_obj << endl;
#endif
#endif
                NrImprovBestObj.at(CurrentMove)++;
                UpdateBestSolution(sol); // We need to store the best solution somewhere
                TimeTillBestSolution = (int)getTimeDiff();
            }
            if (obj <= current_obj){
                // cout << "Accept solution" << endl;
                if (obj < current_obj){
                    Reward.at(CurrentMove) += (current_obj-obj);
                    NrImprov.at(CurrentMove)++;
                    Improv.at(CurrentMove).push_back(current_obj-obj);
                }
            }

	}

template <typename Move>
        void MetaBase<Move>::SaveResultsMoves(std::string file_path_results_base, int instance, int seed){
            std::string file_path_results_performance = file_path_results_base + std::string(PATHSEP) + "Performance" + std::string(PATHSEP) + to_string(instance) + "_" + to_string(seed) + ".txt";
            std::ofstream file(file_path_results_performance);
            file << "Move, NrChosen, NrAccepted, % Times improvement found, Average improvement found, % Times contribution to best objective, Instance, Seed\n";
            // cout << "Move, NrChosen, NrAccepted, % Improvement found, Average improvement found, % contribution to best objective" << endl;
            for (const auto& [move, string_name]: Moves){
                if (string_name == "Initial"){
                    continue;
                }
                // cout << string_name << ", " << NrChosen.at(move) << ", " << NrAccepted.at(move) << ", " << (double) NrImprov.at(move) / (double) NrChosen.at(move) << ", " << (double) Reward.at(move) / (double) NrChosen.at(move) << ", " << (double) NrImprovBestObj.at(move) / (double) NrChosen.at(move)  << endl;
                file << string_name << ",";
                file << NrChosen.at(move) << ",";
                file << NrAccepted.at(move) << ",";
                file << (double) NrImprov.at(move) / (double) NrChosen.at(move) << ",";
                file << (double) Reward.at(move) / (double) NrImprov.at(move) << ",";
                file << (double) NrImprovBestObj.at(move) / (double) NrChosen.at(move) << ",";
                file << instance << "," << seed << "\n";
            }
            file.close();
   
            std::string file_path_results_time= file_path_results_base + std::string(PATHSEP) + "ExecutionTime" + std::string(PATHSEP) + to_string(instance) + "_" + to_string(seed) + ".txt";
            std::ofstream file2(file_path_results_time);
            file2 << "Move,Min,Max,Mean,Instance,Seed\n";
            // cout << "Move, NrChosen, NrAccepted, % Improvement found, Average improvement found, % contribution to best objective" << endl;
            for (const auto& [move, string_name]: Moves){
                if (string_name == "Initial" || ExecutionTimes.at(move).empty()){
                    continue;
                }
                array<std::chrono::microseconds,3>MinMaxMean = MinMaxMeanExecutionTime(move);
                file2 << MinMaxMean[0].count() << ",";
                file2 << MinMaxMean[1].count() << ",";
                file2 << MinMaxMean[2].count() << ",";
                file2 << instance << "," << seed << "\n";
                /*
                for (auto dur: ExecutionTimes.at(move)){ // store these as well to make boxplots later?
                    file2 << dur.count() << "\n";
                }
                */
            }
            file2.close();
        }

template<typename Move>
bool LAHC<Move>::Update(Solution& sol, const int obj) {
           // code based on Burke (2017) "The late acceptance Hill-Climbing Heuristic"
            this->UpdateValues(sol, obj);
            bool SolutionAccepted = false;
            int v = this->it % HistoryLength;
            /*
            cout << "L = ";
            for (int w = 0; w < this->HistoricValues.size(); ++w){
                if (w != v){
                    cout << w << ") " << this->HistoricValues.at(w) << " ";
                }
                else{
                    cout << w << ")** " << this->HistoricValues.at(w) << " ";
                }
            }
            cout << endl;
            cout << "Found obj = " << obj << ", current_obj = " << this->current_obj << ", it_idle = " << this->it_idle << endl;
            */
            if (obj >= this->current_obj){
                this->it_idle++;
            }
            else{
                this->it_idle = 0;
            }
            if (obj <= this->current_obj || obj < HistoricValues.at(v)){
                this->current_obj = obj; 
                this->it_accepted++;
                SolutionAccepted = true;
                // cout << "Accept solution" << endl;
#if PRINT == 1
                this->print_solution();
#endif
            }
            if (obj < HistoricValues.at(v)){
                HistoricValues.at(v) = obj;
            }

            this->UpdateTimeStamps();
	
            if (this->getTimeDiff() > this->TIME_LIMIT || (++this->it > MAX_IT && this->it_idle > this->it*0.02) || (this->LowerBound >= 0 && obj <= this->LowerBoundGap*this->LowerBound)){
                this->STOP = true;
                if (this->getTimeDiff() > this->TIME_LIMIT){
                    cout << "Time limit hit" << endl;
                }
                else if (this->LowerBound >= 0 && obj <= this->LowerBoundGap*this->LowerBound){
                    cout << "Lower bounds = " << this->LowerBound << ", current objective = " << obj << endl;
                }
                else{
                    cout << "max it_idle hit: " << this->it_idle << endl;
                }
            }
            // cin.get();
            return SolutionAccepted;

}

template<typename Move>
bool SA<Move>::Update(Solution& sol, const int obj){
            // cout << "prev_obj = " << current_obj << ", new obj = " << obj << endl;
            this->UpdateValues(sol, obj);
            bool SolutionAccepted = false;
            if (obj <= this->current_obj){
                this->current_obj = obj; 
                this->it_accepted++;
                SolutionAccepted = true;
            }
            else{
                this->dist_real = std::uniform_real_distribution<>(0.0, 1.0);
                double rnd = this->dist_real(this->gen);
                if (rnd <= exp(-(obj-this->current_obj)/T)){ // Metropolis acceptance
                    // cout << "Accept solution with prob " << exp(-(obj-current_obj)/T) << ", prev_obj = " << current_obj << ", new obj = " << obj << endl;
                    this->current_obj = obj;
                    this->it_accepted++;
                    SolutionAccepted = true;
                }
                else{
                    // reverse move
                    // We only need to reverse the haps since the matchings are thrown away anyway
                    // cout << "Reject solution with prob " << exp(-(obj-current_obj)/T) << endl;
                    return false; // CUSTOMIZE WHAT HAPPENS AFTERWARDS
                }
            }
            if (SolutionAccepted){
#ifdef PRINT
#if PRINT == 1
                    this->print_solution();
#endif
#endif
            }

            this->UpdateTimeStamps();

            if (++this->it % I_temp == 0 || this->it_accepted % I_accept == 0){ 
                T *= cooling_rate;
                cout << "New T = " << T << endl;
                this->it_accepted = 0;
                this->it = 0;
            }
            if (this->getTimeDiff() > this->TIME_LIMIT || T < T_end){
                this->STOP = true;
                if (this->getTimeDiff() > this->TIME_LIMIT){
                    cout << "Time limit hit" << endl;
                }
                else{
                    cout << "Final temperature hit after " << this->getTimeDiff() << " seconds" << endl;
                }
                // cin.get();
            }
            return SolutionAccepted;
}


// Explicit instantiations
template class MetaBase<FO_move>;
template class MetaBase<Move>;
template class LAHC<Move>;
template class SA<FO_move>;
template class SA<Move>;
